baseURL = 'https://duck.moe/'
enableGitInfo = true
languageCode = 'en-gb'
title = 'www.duck.'

[outputs]
  home = ['HTML', 'WebAppManifest']

[params]
    Version = "4.2023.2"
    ThemeColor =  "#1fb4eb"
    ThemeColorDark = "#052b39"

[[params.favicons]]
    href = "/favicon.ico"
    sizes = "32x32"
    rel = "icon"
[[params.favicons]]
    href = "/apple-touch-icon.png"
    rel = "apple-touch-icon"
    sizes = "180x180"

[social]
    MastoName = "duck"
    MastoHost = "queer.af"
    GithubName = "duckfullstop"
    DiscordName = "duck"
    DiscordHash = "0001"
    Email = "me@duck.moe"
    MatrixUser = "duck"
    MatrixServer = "duck.moe"

[module]
[module.hugoVersion]
min = "0.92.0"

[[module.imports]]
path="github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
[[module.imports]]
path="github.com/hugo-mods/icons"