baseURL = 'https://duck.moe/'
enableGitInfo = true
languageCode = 'en-gb'
title = 'www.duck.'

[params]
    Version = "4.2023.2"

[social]
    MastoName = "duck"
    MastoHost = "queer.af"
    GithubName = "duckfullstop"
    DiscordName = "duck"
    DiscordHash = "0001"
    Email = "me@duck.moe"
    MatrixUser = "duck"
    MatrixServer = "duck.moe"

[module]
[module.hugoVersion]
min = "0.92.0"

[[module.imports]]
path="github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
[[module.imports]]
path="github.com/hugo-mods/icons"