baseURL = 'https://duck.moe/'
enableGitInfo = true
languageCode = 'en-gb'
title = 'www.duck.'

[params]
    SocialAccNameMastodon = "duck"
    SocialAccHostMastodon = "queer.af"
    SocialAccNameGithub = "duckfullstop"
    SocialAccNameDiscord = "duck"
    SocialAccHashDiscord = "0001"
    SocialAccAddrEmail = "me@duck.moe"

    Version = "4.2023.2"

[module]
[module.hugoVersion]
min = "0.92.0"

[[module.imports]]
path="github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
[[module.imports]]
path="github.com/hugo-mods/icons"